export const cardData = [
  {
    id: 1,
    description: "Master of cursed techniques.",
    hp: 170,
    attackPhysical: 50,
    attackMental: 50,
    defensePhysical: 55,
    defenseSpecial: 50,
    rizz: 1000000,
    ability: "Limitless: Negate attacks once every 3 turns.",
    type: "Sorcerer",
    rarity: "Mythical",
    name: "Gojo Satoru",
    img: "src/assets/Characters/gojo.png",
    isLocked: false,
  },

  {
    id: 2,
    description: "Blood-fueled berserker.",
    hp: 145,
    attackPhysical: 40,
    attackMental: 20,
    defensePhysical: 40,
    defenseSpecial: 25,
    rizz: 5,
    ability: "Chainsaw Frenzy: Extra attack every 2 turns.",
    type: "Fighter",
    rarity: "Epic",
    name: "Denji",
    img: "src/assets/Characters/chainsaw.png",
    isLocked: false,
  },

  {
    id: 3,
    description: "The strongest hero.",
    hp: 200,
    attackPhysical: 50,
    attackMental: 40,
    defensePhysical: 60,
    defenseSpecial: 55,
    rizz: 0,
    ability: "One Punch: Doubles Outgoing Damage.",
    type: "Fighter",
    rarity: "Mythical",
    name: "Saitama",
    img: "src/assets/Characters/saitama.png",
    isLocked: false,
  },

  {
    id: 4,
    description: "Gadget cat from the future.",
    hp: 150,
    attackPhysical: 40,
    attackMental: 60,
    defensePhysical: 50,
    defenseSpecial: 50,
    rizz: 5,
    ability: "Secret Pouch: Grants a Random Buff(Inc Dmg, Heal, Inc Def).",
    type: "Support",
    rarity: "Common",
    name: "Doraemon",
    img: "src/assets/Characters/doraemon.png",
    isLocked: false,
  },

  {
    id: 5,
    description: "Gentle forest spirit.",
    hp: 180,
    attackPhysical: 50,
    attackMental: 10,
    defensePhysical: 80,
    defenseSpecial: 80,
    rizz: 50,
    ability: "Fluffy: Incoming damage is halved.",
    type: "Tank",
    rarity: "Rare",
    name: "Totoro",
    img: "src/assets/Characters/totoro.png",
    isLocked: false,
  },

  {
    id: 6,
    description: "Rubber man with unbreakable will.",
    hp: 130,
    attackPhysical: 50,
    attackMental: 20,
    defensePhysical: 40,
    defenseSpecial: 20,
    rizz: 5,
    ability: "Stubborn: Immune to Mental Damage.",
    type: "Fighter",
    rarity: "Rare",
    name: "Luffy",
    img: "src/assets/Characters/luffy.png",
    isLocked: false,
  },

  {
    id: 7,
    description: "Elite soldier with strong resolve.",
    hp: 150,
    attackPhysical: 65,
    attackMental: 65,
    defensePhysical: 30,
    defenseSpecial: 30,
    rizz: 20,
    ability: "Normy: Nothing special.",
    type: "Fighter",
    rarity: "Epic",
    name: "Mikasa",
    img: "src/assets/Characters/mikasa.png",
    isLocked: false,
  },

  {
    id: 8,
    description: "Innocent but powerful cutie.",
    hp: 100,
    attackPhysical: 1,
    attackMental: 80,
    defensePhysical: 20,
    defenseSpecial: 20,
    rizz: 99,
    ability: "Cute: Gives teammate a buff",
    type: "Support",
    rarity: "Common",
    name: "Chiikawa",
    img: "src/assets/Characters/chiikawa.png",
    isLocked: false,
  },

  {
    id: 9,
    description: "You are my sunshine.",
    hp: 170,
    attackPhysical: 45,
    attackMental: 40,
    defensePhysical: 65,
    defenseSpecial: 55,
    rizz: 10,
    ability: "Sunshine: You are my sunshine",
    type: "Athlete",
    rarity: "Epic",
    name: "Lebron James",
    img: "src/assets/Characters/lebron.png",
    isLocked: false,
  },

  {
    id: 10,
    description: "Cursed old speedster.",
    hp: 150,
    attackPhysical: 45,
    attackMental: 45,
    defensePhysical: 70,
    defenseSpecial: 45,
    rizz: -1,
    ability: "Ghost Rush: Increases speed.",
    type: "Spirit",
    rarity: "Epic",
    name: "Turbo Granny",
    img: "src/assets/Characters/turbogran.png",
    isLocked: false,
  },

  {
    id: 11,
    description: "Just a regular shinobi (believe it!)",
    hp: 150,
    attackPhysical: 65,
    attackMental: 65,
    defensePhysical: 30,
    defenseSpecial: 30,
    rizz: 1,
    ability: "Kurama: Attacks twice",
    type: "Ninja",
    rarity: "Uncommon",
    name: "Naruto",
    img: "src/assets/Characters/naruto.png",
    isLocked: false,
  },
];
